// Map marker types
export type MapMarkerCategory =
  | 'library'
  | 'canteen'
  | 'dorm'
  | 'supermarket'
  | 'bank'
  | 'restaurant'
  | 'danger'
  | 'safety'
  | 'gym'
  | 'sports'
  | 'hospital'
  | 'pharmacy'
  | 'lab'
  | 'computer_lab'
  | 'classroom'
  | 'parking'
  | 'bus_stop'
  | 'metro'
  | 'garden'
  | 'student_center'
  | 'career_center'
  | 'printing'
  | 'delivery'
  | 'barber'
  | 'swimming'
  | 'music'
  | 'art_studio'
  | 'counseling'
  | 'international_office'
  | 'dormitory_office'
  | 'teaching_building'
  | 'research_center'
  | 'study_room'
  | 'cafe'
  | 'bookstore'
  | 'gymnasium'
  | 'stadium'
  | 'playground'
  | 'basketball'
  | 'tennis'
  | 'health_center'
  | 'admissions'
  | 'financial_aid'
  | 'library_lab'
  | 'shuttle'
  | 'nightlife'
  | 'bar'
  | 'ktv'
  | 'cinema'
  | 'dating'
  | 'love_hotel'
  | 'Convenience Store'
  | 'laundry'
  | 'pc_cafe'
  | 'photography'
  | 'fitness_room'
  | 'rooftop'
  | 'scenic_spot'
  | 'other';

export interface MapMarker {
  id: string;
  universityId: string;
  universityName: string;
  name: string;
  nameZh: string;
  category: MapMarkerCategory;
  description: string;
  descriptionZh: string;
  coordinates: {
    lat: number;
    lng: number;
  };
  images: string[];
  rating: number;
  ratingCount: number;
  tags: string[];
  createdAt: string;
}

// Category icon emoji mapping
export const CATEGORY_ICONS: Record<MapMarkerCategory, string> = {
  library: '📚',
  canteen: '🍜',
  dorm: '🏠',
  supermarket: '🛒',
  bank: '🏦',
  restaurant: '🍽️',
  danger: '⚠️',
  safety: '✅',
  gym: '🏋️',
  sports: '⚽',
  hospital: '🏥',
  pharmacy: '💊',
  lab: '🔬',
  computer_lab: '💻',
  classroom: '🏫',
  parking: '🅿️',
  bus_stop: '🚌',
  metro: '🚇',
  garden: '🌳',
  student_center: '🎓',
  career_center: '💼',
  printing: '🖨️',
  delivery: '📦',
  barber: '💇',
  swimming: '🏊',
  music: '🎵',
  art_studio: '🎨',
  counseling: '🧠',
  international_office: '🌍',
  dormitory_office: '🏢',
  teaching_building: '🏛️',
  research_center: '🔭',
  study_room: '📖',
  cafe: '☕',
  bookstore: '📕',
  gymnasium: '🏟️',
  stadium: '🏟️',
  playground: '🛝',
  basketball: '🏀',
  tennis: '🎾',
  health_center: '🩺',
  admissions: '🎫',
  financial_aid: '💰',
  library_lab: '💻',
  shuttle: '🚌',
  nightlife: '🌙',
  bar: '🍺',
  ktv: '🎤',
  cinema: '🎬',
  dating: '💑',
  love_hotel: '💕',
  'Convenience Store': '🏪',
  laundry: '🧺',
  pc_cafe: '🎮',
  photography: '📷',
  fitness_room: '🏃',
  rooftop: '🌆',
  scenic_spot: '🌅',
  other: '📍',
};

// Category display names (i18n keys would go here in real app)
export const CATEGORY_NAMES: Record<MapMarkerCategory, string> = {
  library: '图书馆',
  canteen: '食堂',
  dorm: '宿舍',
  supermarket: '超市',
  bank: '银行',
  restaurant: '餐厅',
  danger: '危险区域',
  safety: '安全区域',
  gym: '健身房',
  sports: '运动场',
  hospital: '医院',
  pharmacy: '药房',
  lab: '实验室',
  computer_lab: '计算机室',
  classroom: '教室',
  parking: '停车场',
  bus_stop: '公交站',
  metro: '地铁站',
  garden: '花园',
  student_center: '学生活动中心',
  career_center: '就业中心',
  printing: '打印店',
  delivery: '快递/蜂巢',
  barber: '理发店',
  swimming: '游泳池',
  music: '音乐室',
  art_studio: '艺术工作室',
  counseling: '心理咨询',
  international_office: '国际学生办公室',
  dormitory_office: '宿舍管理办公室',
  teaching_building: '教学楼',
  research_center: '研究中心',
  study_room: '自习室',
  cafe: '咖啡厅',
  bookstore: '书店',
  gymnasium: '体育馆',
  stadium: '体育场',
  playground: '操场',
  basketball: '篮球场',
  tennis: '网球场',
  health_center: '校医院',
  admissions: '招生办公室',
  financial_aid: '助学贷款办公室',
  library_lab: '图书馆电子阅览室',
  shuttle: '校巴站',
  nightlife: '夜生活',
  bar: '酒吧',
  ktv: 'KTV',
  cinema: '电影院',
  dating: '约会地点',
  love_hotel: '情侣酒店',
  'Convenience Store': '便利店',
  laundry: '自助洗衣',
  pc_cafe: '网吧',
  photography: '照相馆',
  fitness_room: '健身房',
  rooftop: '天台',
  scenic_spot: '风景点',
  other: '其它',
};
